### ISSUE TITLE
low/high swapped

### ISSUE THREAD

**Issue by Schmieta** [diegojromerolopez/djbdd#2]
Hi all,

during a unit test of TableT.write and TableT.fromBufferedReader I found low and high were swapped in fromBufferedReader:
```
// Second loop, we set low and high descendants
	for (Integer key : tempT.keySet()) {
	Vertex v = tempT.get(key);
	if (!v.isLeaf()) {
		Vertex low = tempT.get(lows.get(v.index));
						Vertex high = tempT.get(highs.get(v.index));
						v.setHigh(low);
						v.setLow(high);
					}
				}
```
It should be called 
```
v.setHigh(high);
v.setLow(low);
```

**Comment by diegojromerolopez** [comment]
@Schmieta what is the file you are trying to read/write? It's been a while since I last worked on this project.

**Comment by Schmieta** [comment]
Hi Diego J.

 

I did not work with files. I hust made a simple JUnit closed loop test:

- write Table X to a StringBuffer or Printer

- read content into Table Y

- compare X and Y by Junit assertions.

 

best regards,

 

Carsten Schmieta

 

 

 

 

 

 

Gesendet: Donnerstag, 25. Januar 2018 um 21:58 Uhr
Von: "Diego J." <notifications@github.com>
An: diegojromerolopez/djbdd <djbdd@noreply.github.com>
Cc: Schmieta <carsten.schmieta@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [diegojromerolopez/djbdd] low/high swapped (#2)


@Schmieta what is the file you are trying to read/write? It's been a while since I last worked on this project.

**Comment by diegojromerolopez** [comment]
Hello Schmieta.

I've already pushed your fix to master.

Thank you very much.

If you have any other issue, don't hesitate to write me again.
